# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='Post',
        ),
    ]
